
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - sensor:
      - name: "Grid L1 Power Signed"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        icon: mdi:transmission-tower-export
        state: >
          {% set raw = states('sensor.srne_grid_l1_power') | int(0) %}
          {% if raw > 32767 %}
            {{ (raw - 65536) * -1 }}
          {% else %}
            {{ raw * -1 }}
          {% endif %}
